// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Saasy.Tenancy.Infrastructure;

#nullable disable

namespace Saasy.Tenancy.Infrastructure.Migrations
{
    [DbContext(typeof(TenancyDbContext))]
    [Migration("20260510154351_AddAuditLogTable")]
    partial class AddAuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Saasy.Tenancy.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_ref");

                    b.Property<Guid>("IntegratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrator_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IntegratorId", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("IX_customers_integrator_id_external_ref");

                    b.ToTable("customers", "tenancy");
                });

            modelBuilder.Entity("Saasy.Tenancy.Domain.Integrators.Integrator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("integrators", "tenancy");
                });

            modelBuilder.Entity("Saasy.Tenancy.Infrastructure.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<Guid?>("IntegratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrator_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("IntegratorId", "Timestamp")
                        .HasDatabaseName("IX_audit_log_integrator_id_timestamp");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_audit_log_target_type_target_id");

                    b.ToTable("audit_log", "tenancy");
                });

            modelBuilder.Entity("Saasy.Tenancy.Infrastructure.SchemaVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchemaVersions", "tenancy");
                });

            modelBuilder.Entity("Saasy.Tenancy.Domain.Integrators.Integrator", b =>
                {
                    b.OwnsMany("Saasy.Tenancy.Domain.Integrators.ApiKey", "ApiKeys", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("HashedSecret")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("hashed_secret");

                            b1.Property<string>("Last4")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("last4");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("integrator_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("integrator_id");

                            b1.ToTable("api_keys", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("integrator_id");
                        });

                    b.OwnsMany("Saasy.Tenancy.Domain.Integrators.IngestionCredential", "IngestionCredentials", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("EncryptedConnectionString")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("encrypted_connection_string");

                            b1.Property<Guid>("integrator_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("integrator_id");

                            b1.ToTable("ingestion_credentials", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("integrator_id");
                        });

                    b.Navigation("ApiKeys");

                    b.Navigation("IngestionCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
